Use Babel + prep up for NPM
roots/js-dom-router pull request #1
Opened 2019-05-04 20:17 UTC by knowler

* Use Babel to compile since we’re using ES6 syntax
* Rename main script to `index.js`
* Move `utils/camelCase.js` to `utils.js` and use named export
* Add `.npmignore` so we don’t publish unnecessary files/directories
* Add [np](https://github.com/sindresorhus/np) since publishing to NPM is error prone (publish whats in your current directory — doesn’t build or clean first). np also handles GitHub tagging/versioning/releasing.

2019-05-04 21:43 UTC, austinpray requested changes
named exports are better

2019-05-04 21:43 UTC, austinpray commented on index.js
> +export default class {
```suggestion
export class Router {
```

2019-05-04 21:47 UTC, knowler commented on index.js
> +export default class {
Cool, I agree.

2019-05-05 04:38 UTC, QWp6t commented
we won't need .npmignore after rewrite

2019-05-05 04:49 UTC, knowler commented
@QWp6t I guess the only thing that would matter after the rewrite is `np`. Do we want to use that for releases/versioning and stuff?

2019-05-05 05:10 UTC, Log1x commented
I'd say roll a GitHub action for it instead.

2019-05-05 05:57 UTC, QWp6t commented
I've never used a GitHub action, but [I have used travis to handle deployments](https://github.com/QWp6t/browsersync-webpack-plugin/blob/master/.travis.yml#L9-L16) when a new release gets tagged.

2019-05-06 19:12 UTC, knowler commented
Travis or a GitHub Action seem more foolproof to me. Closing this.

2019-05-06 19:12 UTC, closed without merging